remote_theme: just-the-docs/just-the-docs
title: TmC0sm Blog 
description: Technical notes on cyber investigations, research and discoveries




# Navigation order in sidebar
nav_order:
  - index.md
  - topics/hunting/
  - topics/experiments/

# Sidebar navigation titles for folders
nav:
  topics/hunting:
    title: Hunting
  topics/experiments:
    title: Experiments
 

# Sort navigation case-insensitive
nav_sort: case_insensitive

# Theme options
theme:
  search_enabled: true
